version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
    depends_on:
      db:
        condition: service_healthy