// Package view provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package view

import (
	"time"
)

// Song defines model for Song.
type Song struct {
	CreatedAt   time.Time `json:"createdAt"`
	DeletedAt   time.Time `json:"deletedAt"`
	Group       string    `json:"group"`
	Id          int       `json:"id"`
	Link        string    `json:"link"`
	ReleaseDate time.Time `json:"releaseDate"`
	Song        string    `json:"song"`
	Text        string    `json:"text"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// Список песен
type SongsByIdResult struct {
	Data Song `json:"data"`
}

// Список песен
type SongsListResult struct {
	Data []Song `json:"data"`
}

// SongsByIdResponse defines model for SongsByIdResponse.
type SongsByIdResponse struct {
	Data Song `json:"data"`
}

// SongsListResponse defines model for SongsListResponse.
type SongsListResponse struct {
	Data []Song `json:"data"`
}

// GetAllSongsParams defines parameters for GetAllSongs.
type GetAllSongsParams struct {
	// Номер страницы
	Page *int `form:"page,default=1" json:"page,omitempty"`

	// Количество сущностей на странице
	PerPage *int `binding:"lte=1000" form:"perPage,default=15" json:"perPage,omitempty"`
}
