// Package view provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package view

// PostSongRequest defines model for PostSongRequest.
type PostSongRequest struct {
	// Название группы
	Group string `binding:"required" json:"group"`

	// Название песни
	Song string `binding:"required" json:"song"`
}

// PutSongRequest defines model for PutSongRequest.
type PutSongRequest struct {
	// Название группы
	Group *string `binding:"omitempty" json:"group,omitempty"`

	// Ссылка на песню
	Link *string `binding:"omitempty" json:"link,omitempty"`

	// Дата релиза
	ReleaseDate *string `binding:"omitempty" json:"releaseDate,omitempty"`

	// Название песни
	Song *string `binding:"omitempty" json:"song,omitempty"`

	// ИД песни
	SongID int `binding:"required" json:"songID"`

	// Куплеты песни
	Text *string `binding:"omitempty" json:"text,omitempty"`
}

// Song defines model for Song.
type Song struct {
	Group       string `json:"group"`
	Id          int    `json:"id"`
	Link        string `json:"link"`
	ReleaseDate string `json:"releaseDate"`
	Song        string `json:"song"`
	Text        string `json:"text"`
}

// Список песен
type SongsByIdResult struct {
	Data Song `json:"data"`
}

// Список песен
type SongsListResult struct {
	Data []Song `json:"data"`
}

// SongsByIdResponse defines model for SongsByIdResponse.
type SongsByIdResponse struct {
	Data Song `json:"data"`
}

// SongsListResponse defines model for SongsListResponse.
type SongsListResponse struct {
	Data []Song `json:"data"`
}

// PostSongJSONBody defines parameters for PostSong.
type PostSongJSONBody = PostSongRequest

// PutSongJSONBody defines parameters for PutSong.
type PutSongJSONBody = PutSongRequest

// GetAllSongsParams defines parameters for GetAllSongs.
type GetAllSongsParams struct {
	// Номер страницы
	Page *int `form:"page,default=1" json:"page,omitempty"`

	// Количество сущностей на странице
	PerPage *int `binding:"lte=1000" form:"perPage,default=15" json:"perPage,omitempty"`
}

// PostSongJSONRequestBody defines body for PostSong for application/json ContentType.
type PostSongJSONRequestBody = PostSongJSONBody

// PutSongJSONRequestBody defines body for PutSong for application/json ContentType.
type PutSongJSONRequestBody = PutSongJSONBody
