openapi: 3.0.3
info:
  title: Songs API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local env
paths:
  /api/v1/songs:
    $ref: "routes/Song.yaml#/paths/AllSongs"
  /api/v1/song/{id}:
    $ref: "routes/Song.yaml#/paths/SongByID"
  /api/v1/song:
    $ref: "routes/Song.yaml#/paths/Song"

components:
  responses:
    ErrorResponse:
      description: Простая ошибка
      properties:
        message:
          type: string
          description: Текст ошибки
          example: Текст ошибки