name: CI for Go api

on:
  push:
    branches:
      - "*"

jobs:
  format_and_check_possible_static_errors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run GOIMPORTS
        run: go run golang.org/x/tools/cmd/goimports@latest -w -l .

      - name: Run GOFUMPT
        run: go run mvdan.cc/gofumpt@latest -w -l .

      - name: Run GOLINES
        run: go run github.com/segmentio/golines@latest -w --no-reformat-tags --max-len=120 .

      - name: Run golangci_lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --timeout 360s


  test:
    runs-on: ubuntu-latest
    needs: format_and_check_possible_static_errors
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Test Go api
        run: go test -v ./...