name: Continuous Integration for Go simple api

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  format_and_check_possible_static_errors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install golangci_lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2

      - name: Run golangci_lint
        run: golangci-lint run --timeout 360s

      - name: Run GOIMPORTS
        run: go run golang.org/x/tools/cmd/goimports@v0.1.11 -w -l .

      - name: Run GOFUMPT
        run: go run mvdan.cc/gofumpt@v0.5.0 -w -l .

      - name: Run GOLINES
        run: go run github.com/segmentio/golines@v0.11.0 -w --no-reformat-tags --max-len=120 .


  test:
    runs-on: ubuntu-latest
    needs: format_and_check_possible_static_errors
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Test Go api
        run: go test -v ./...